### ISSUE TITLE
link locality to area

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#706] opened 2022-01-22 22:57 UTC
It should be possible to assign locality to area. This relation would allow retrieving information for e.g., mineral deposits.
Add field area to locality form before mindat field.

**Comment by ollehints** [comment] 2022-01-22 22:59
database updated with area_id field

**Comment by enmust** [comment] 2022-03-31 09:13
Problem with migrations, can't add field to locality table as it throws a weird error saying 'invalid default value for "date_added"'

**Comment by enmust** [comment] 2024-01-10 11:13
Duplicate of #763

**Closed by enmust** 2024-01-10 11:13 UTC
Labels: enhancement
